### ISSUE TITLE
Error when migrate

### ISSUE THREAD

**Issue by paulocoutinhox** [ncunx/eCommerce-django#23]
python3 manage.py migrate --settings=src.settings.local
Traceback (most recent call last):
  File "/Users/paulo/Developer/workspaces/python/ecommerce-backend/accounts/api/serializers.py", line 8, in <module>
    from allauth.utils import email_address_exists
ImportError: cannot import name 'email_address_exists' from 'allauth.utils' (/Users/paulo/Library/Python/3.9/lib/python/site-packages/allauth/utils.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/paulo/Developer/workspaces/python/ecommerce-backend/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/paulo/Developer/workspaces/python/ecommerce-backend/src/urls.py", line 24, in <module>
    path("api/", include("api.urls")),
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/paulo/Developer/workspaces/python/ecommerce-backend/api/urls.py", line 4, in <module>
    path("accounts/", include("accounts.api.urls")),
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/paulo/Developer/workspaces/python/ecommerce-backend/accounts/api/urls.py", line 3, in <module>
    from .views import CustomRegisterView
  File "/Users/paulo/Developer/workspaces/python/ecommerce-backend/accounts/api/views.py", line 1, in <module>
    from rest_auth.registration.views import RegisterView
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/rest_auth/registration/views.py", line 22, in <module>
    from rest_auth.app_settings import (TokenSerializer,
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/rest_auth/app_settings.py", line 24, in <module>
    UserDetailsSerializer = import_callable(
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/rest_auth/utils.py", line 11, in import_callable
    return getattr(import_module(package), attr)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/paulo/Developer/workspaces/python/ecommerce-backend/accounts/api/serializers.py", line 10, in <module>
    raise ImportError("allauth needs to be added to INSTALLED_APPS.")
ImportError: allauth needs to be added to INSTALLED_APPS.

**Comment by kkosiba** [comment]
Looks like https://github.com/kkosiba/ecommerce-backend/pull/21 should fix this.

**Comment by WajahatKanju** [comment]
Close the issue if it has been fixed.

**Comment by Samcool1990** [comment]
To resolve this issue, follow these steps:

Add allauth to INSTALLED_APPS: Make sure that the allauth app is included in the INSTALLED_APPS setting in your Django project's settings.py file. You can add it like this:
INSTALLED_APPS = [
    # other apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # other apps
]
Install django-allauth: If you haven't already installed django-allauth, you need to do so. You can install it using pip:
pip install django-allauth



Check django-allauth Version Compatibility: Ensure that the version of django-allauth you've installed is compatible with your Django version. You can check the compatibility in the documentation or release notes of django-allauth.


Check settings.py for Errors: Review your settings.py file to ensure that there are no syntax errors or typos in the INSTALLED_APPS setting or any other relevant settings related to allauth.


Import email_address_exists from Correct Location: If you still encounter the ImportError after adding allauth to INSTALLED_APPS, ensure that the email_address_exists function is available in the version of django-allauth you are using. Check the documentation or source code of django-allauth to find the correct location of the email_address_exists function.
